version: '3.3'

services:

  jira:
    image: atlassian/jira-software
    container_name: jira
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - JVM_MINIMUM_MEMORY=512m
      - JVM_MAXIMUM_MEMORY=2048m
 #     - ATL_PROXY_NAME=jira.example.com
 #     - ATL_PROXY_PORT=443
 #     - ATL_TOMCAT_SCHEME=https
 #     - ATL_TOMCAT_SECURE=true
 #     - ATL_AUTOLOGIN_COOKIE_AGE=2592000 # 30 days in seconds
    ports:
      - "8200:8080"
    volumes:
      - ./data:/var/atlassian/application-data/jira

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dbuser1
      - POSTGRES_PASSWORD=dbpass1